#!/usr/bin/env ruby
# encoding: UTF-8
# (C) 2014, Antoine Catton <devel@antoine.catton.fr> (See license file)

require_relative 'src/report'
require_relative 'src/parser'

options = TLSReport::OptionParser.parse ARGV
puts TLSReport::TLS::Report.new options
